/**
 * Style note: Field Notes for Better Work — privacy terms are candid operational records,
 * with current practice separated from future advertising configuration.
 */
import { CircleAlert, Cookie, ExternalLink, FileText, ShieldCheck } from "lucide-react";
import Layout from "@/components/Layout";
import { SeoMeta } from "@/components/SeoMeta";
import { useCookieConsent } from "@/components/CookieConsent";
import PrivacyEnhancements from "@/components/PrivacyEnhancements";
import SiteBreadcrumb, { breadcrumbListSchema } from "@/components/SiteBreadcrumb";

const effectiveDate = "15 August 2026";
const policyLinks = [
  { href: "#information", label: "Information" },
  { href: "#cookies", label: "Cookies" },
  { href: "#advertising", label: "Advertising" },
  { href: "#rights", label: "Your choices" },
  { href: "#contact", label: "Contact" },
];

export default function Privacy() {
  const { consent, openSettings } = useCookieConsent();
  const preferenceText = !consent
    ? "No optional choice has been saved on this device."
    : `Saved ${new Date(consent.updatedAt).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}: site analytics ${consent.analytics ? "allowed" : "rejected"}. Google advertising consent is not managed by this control.`;

  return <Layout>
    <SeoMeta title="Privacy policy & cookie notice" description="Workflow Library's privacy policy for Cookie choices, optional analytics, Google AdSense base code, and the advertising consent route used for applicable regions." schema={({ origin, pageUrl }) => breadcrumbListSchema(origin, pageUrl, [{ label: "Home", href: "/" }, { label: "Privacy policy" }])} />
    <PrivacyEnhancements />
    <section className="legal-page privacy-policy-page">
      <span className="eyebrow">Privacy policy · Cookie notice</span>
      <h1>Plain language about<br />data and choices.</h1>
      <p className="legal-lede">Effective date: {effectiveDate}. This is Workflow Library’s public privacy record. It separates site-analytics choices from the certified Google advertising-consent route that applies when advertising is served.</p>

      <div className="privacy-policy-record" aria-label="Current privacy policy status">
        <div><strong>Scope</strong><span>Public educational website, Cookie controls, and optional analytics.</span></div>
        <div><strong>Current status</strong><span>No accounts, payments, messages, newsletters, or manual in-content ad units are active. The Google AdSense base code is installed.</span></div>
        <div><strong>Reader control</strong><span>Site analytics stays off until a reader makes a choice and can be changed any time.</span></div>
      </div>

      <nav className="privacy-toc" aria-label="Privacy policy sections"><span><FileText size={16} /> Reading guide</span><div>{policyLinks.map((item) => <a key={item.href} href={item.href}>{item.label}</a>)}</div></nav>
      <div className="privacy-choice-panel"><div><ShieldCheck size={23} /><div><span className="eyebrow">Your current browser choice</span><p>{preferenceText}</p></div></div><button type="button" className="primary-button" onClick={openSettings}>Manage cookie choices</button></div>
      <aside className="privacy-implementation-note" aria-label="Publisher information"><CircleAlert size={19} /><div><strong>Publisher information.</strong><p>Workflow Library is published under the Knexio site brand. Privacy questions can be sent to <a href="mailto:tzhkai6@gmail.com">tzhkai6@gmail.com</a>. If a jurisdiction requires a legal entity name, registered address, or another disclosure, the publisher will add that information here before it applies.</p></div></aside>

      <div className="legal-content">
        <section id="scope"><div><h2>Scope of this policy</h2><p>This policy applies to the public pages of Workflow Library at <strong>knexio.xyz</strong>. Workflow Library is an independent educational publishing project for practical AI workflows in research, writing, meetings, and planning. It does not govern third-party services a reader chooses to visit through an external link.</p><p>The public edition is designed for reading. It does not invite visitors to create accounts, submit comments, upload files, pay for a service, or subscribe to a newsletter.</p></div></section>
        <section id="information"><div><h2>Information handled today</h2><p>The Site does not ask visitors for names, email addresses, passwords, payment details, health information, identity documents, or message contents. Ordinary technical request information may be processed to deliver a web page, including browser type, device characteristics, referring page, request time, page address, IP address, and approximate location derived from IP address.</p><p>The Site stores one necessary local-storage record named <strong>workflow-library-cookie-consent-v1</strong>. It records the browser’s optional Cookie choices, the time of that choice, and a 180-day expiry. It is used to remember the choice on that browser and is not designed to identify a person.</p></div></section>
        <section id="cookies"><div><h2>Cookies and local storage</h2><p>Necessary local storage saves a reader’s consent choice. Optional site analytics is loaded only after a reader allows it through the Cookie banner or Cookie settings. The Site’s custom Cookie control does not collect or store a Google advertising choice.</p><p>You can use <button type="button" className="inline-policy-button" onClick={openSettings}>Cookie settings</button> on this page or in the footer to accept, reject, or change site-analytics choices. Changing a choice affects future optional script loading on that browser. Browser controls may also allow you to clear or block storage; doing so can reset saved preferences.</p></div></section>
        <section id="analytics"><div><h2>Optional analytics</h2><p>Optional analytics is off unless a reader chooses it. When enabled, the Site may load its configured usage-measurement script to understand aggregated navigation and page-use patterns. The analytics provider, data location, and retention setting must be named here before that feature is publicly activated.</p><p>Rejecting analytics does not prevent a reader from browsing guides, copying a starting prompt, opening internal links, or changing Cookie preferences later.</p></div></section>
        <section id="advertising"><div><h2>Advertising and Google AdSense</h2><p>The Google AdSense base script is installed on the Site for site connection, verification, and the advertising service when eligible. Workflow Library does not currently place manual in-content ad units, remarketing tags, or separate advertising-measurement tags. The publisher reports that a Google Privacy &amp; messaging European regulations message has been published for the Site. The Site’s separate Cookie control remains limited to site analytics so it does not duplicate or override the certified advertising consent flow.</p><p>Google states that its advertising technologies may use cookies and related information for functions such as advertising relevance, frequency control, and reporting. Readers can review how Google uses data when they use partners’ sites or apps at <a href="https://business.safety.google/privacy/" target="_blank" rel="noreferrer">Google’s Business Data Responsibility page <ExternalLink size={13} /></a> and manage eligible ad-personalization settings through <a href="https://myadcenter.google.com/" target="_blank" rel="noreferrer">My Ad Center <ExternalLink size={13} /></a>.</p></div></section>
        <section id="regional-consent"><div><h2>EEA, UK, and Switzerland</h2><p>A simple in-site preference banner is not a substitute for the consent infrastructure required for personalized Google advertising in the EEA, the United Kingdom, and Switzerland. The publisher reports that the Site’s Google Privacy &amp; messaging European regulations message is published. Where applicable, that message is the advertising-consent route and is expected to identify relevant purposes, participating parties, reader choices, and a withdrawal route.</p><p>The publisher should verify the published message from an eligible EEA, UK, or Swiss test location or through the Google Privacy &amp; messaging preview before serving advertising in those regions.</p></div></section>
        <section id="sharing"><div><h2>Sharing, sale, and external links</h2><p>Workflow Library does not sell or share personal information for cross-context behavioral advertising, and no targeted advertising or data-broker sharing feature is active in the current edition. The site does not operate a reader profile, advertising audience, or newsletter list.</p><p>Article sharing controls may create a link, open an email draft, open a selected social platform, or invoke a browser or device’s native sharing feature. Workflow Library does not add a third-party sharing widget or share tracker. A reader who chooses an external sharing destination is subject to that destination’s terms and privacy notice.</p><p>Following an external link is voluntary. Workflow Library does not control the privacy practices, content, or availability of third-party services. If advertising or another sharing practice changes, this notice and the applicable consent route will be updated before the new processing begins.</p></div></section>
        <section id="retention"><div><h2>Retention</h2><p>The local consent record expires after 180 days unless it is changed, cleared, or removed by the browser sooner. The Site does not maintain a reader-submission database in the current edition.</p><p>If analytics, advertising, a contact form, an account, or another direct-collection feature is activated, this policy will state the applicable retention period or a clear link to the processor’s retention information before that feature begins processing reader information.</p></div></section>
        <section id="rights"><div><h2>Your choices and requests</h2><p>You can change optional Cookie choices at any time using <button type="button" className="inline-policy-button" onClick={openSettings}>Cookie settings</button>. Depending on where you live, applicable privacy law may provide rights to request access, correction, deletion, restriction, objection, portability, or withdrawal of consent for certain personal information.</p><p>Before a feature that collects personal information is enabled, the publisher will add a genuine, monitored privacy contact route for applicable requests. Do not send sensitive information through an unverified channel.</p></div></section>
        <section id="security"><div><h2>Security and children</h2><p>The publisher uses reasonable technical measures appropriate to the services actually enabled. However, no internet transmission or storage method can be guaranteed completely secure.</p><p>The Site is not directed at children and does not knowingly invite children to submit personal information. If direct collection features are added, the publisher will review the relevant age and consent requirements before activation.</p></div></section>
        <section id="changes"><div><h2>Changes to this policy</h2><p>The effective date above changes when this policy changes substantively. Material changes include activating an advertising provider, contact form, account, newsletter, analytics provider, or new sharing technology. The revised version will be published here before or when the relevant processing begins, as required by applicable law.</p></div></section>
        <section id="contact"><div><h2>Privacy contact</h2><p>Workflow Library does not currently offer a direct-collection feature. The Site is published under the Knexio site brand, and the privacy contact route below is monitored for privacy questions, Cookie concerns, and requests related to this policy.</p><p><strong>Site publisher (brand name):</strong> Knexio<br /><strong>Privacy contact:</strong> <a href="mailto:tzhkai6@gmail.com">tzhkai6@gmail.com</a></p></div></section>
      </div>

      <section className="privacy-sources" aria-labelledby="privacy-references-heading"><Cookie size={20} /><div><span className="eyebrow" id="privacy-references-heading">Official advertising references</span><p><a href="https://business.safety.google/privacy/" target="_blank" rel="noreferrer">Google’s Business Data Responsibility</a> · <a href="https://support.google.com/adsense/answer/7549925?hl=en" target="_blank" rel="noreferrer">How AdSense uses cookies</a> · <a href="https://www.google.com/about/company/user-consent-policy/" target="_blank" rel="noreferrer">Google EU user consent policy</a> · <a href="https://support.google.com/adsense/answer/13554116?hl=en" target="_blank" rel="noreferrer">Google CMP requirements for publishers</a></p></div></section>
    </section>
  </Layout>;
}
