/**
 * Style note: Field Notes for Better Work — privacy information is a readable operational record,
 * with real current behavior separated from future advertising configuration.
 */
import { Cookie, ExternalLink, ShieldCheck } from "lucide-react";
import Layout from "@/components/Layout";
import { SeoMeta } from "@/components/SeoMeta";
import { useCookieConsent } from "@/components/CookieConsent";
import PrivacyEnhancements from "@/components/PrivacyEnhancements";

export default function Privacy() {
  const { consent, openSettings } = useCookieConsent();
  const preferenceText = !consent ? "You have not saved a choice yet." : `Saved ${new Date(consent.updatedAt).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}: analytics ${consent.analytics ? "allowed" : "rejected"}; advertising ${consent.advertising ? "allowed" : "rejected"}.`;
  return <Layout><SeoMeta title="Privacy & cookie notice" description="Workflow Library's transparent notice for consent choices, optional analytics, and future disclosed advertising technology." /><PrivacyEnhancements />
    <section className="legal-page"><span className="eyebrow">Privacy & cookie notice</span><h1>Plain language about<br />data and choices.</h1><p className="legal-lede">Last updated: August 14, 2026. This notice describes the website’s current behavior. Before public launch, the publisher must replace the unfinished operator and contact details with accurate information for the final domain and jurisdictions served.</p>
      <div className="privacy-choice-panel"><div><ShieldCheck size={23} /><div><span className="eyebrow">Your current browser choice</span><p>{preferenceText}</p></div></div><button type="button" className="primary-button" onClick={openSettings}>Manage cookie choices</button></div>
      <div className="legal-content">
        <section><h2>1. Who is responsible for this site</h2><p>Workflow Library is operated by its publisher. The public publisher identity and a working privacy contact channel must be added before launch in the About and Contact pages. Until those real details are published, this website should be treated as a pre-launch demonstration rather than a completed public privacy notice.</p></section>
        <section><h2>2. What this site stores now</h2><p>This site stores one necessary local-storage record named <strong>workflow-library-cookie-consent-v1</strong>. It contains the visitor’s choices for necessary preferences, analytics, and advertising, together with a timestamp and a 180-day expiry. It is used only to remember the choice in this browser. It does not contain a name, email address, account, payment detail, or message content.</p></section>
        <section><h2>3. Optional analytics</h2><p>Optional analytics is off until the visitor enables it through the consent banner or Cookie settings. If enabled, the site loads its configured usage-measurement script to understand aggregated navigation and page-use patterns. The publisher must identify the actual analytics provider, configured retention period, and any provider-specific data practices here before public launch. Rejecting optional analytics does not block access to articles or core navigation.</p></section>
        <section><h2>4. Advertising and Google technology</h2><p>No Google AdSense ad code or advertising technology is active in this version. If the publisher enables AdSense later, Google and relevant advertising partners may use cookies or other local storage for ad delivery, frequency control, measurement, fraud prevention, and—where consent and settings permit—ad personalization. The publisher must update this notice with the active providers and provide the required consent journey before those tags load.</p><p>Visitors can manage Google ad personalization through Google’s <a href="https://myadcenter.google.com/" target="_blank" rel="noreferrer">My Ad Center <ExternalLink size={13} /></a>. Google explains that AdSense publishers must display a privacy policy about cookie use, and Google’s EU policy requires appropriate consent, records, and revocation instructions where applicable.</p></section>
        <section><h2>5. EEA, UK, and Switzerland visitors</h2><p>For personalized Google ads in the EEA, the UK, and Switzerland, a simple in-site banner is not a substitute for the required advertising consent infrastructure. Before serving personalized ads in those regions, the publisher should use Google Privacy & messaging or another Google-certified CMP integrated with the IAB Transparency and Consent Framework, then keep the provider list and regional disclosures in this notice accurate.</p></section>
        <section><h2>6. Sharing and service providers</h2><p>This version does not provide accounts, newsletter sign-up, comments, payments, or contact-form submission. If the publisher later adds analytics, advertising, hosting, embedded media, email, forms, or other services, each provider and its role must be listed here before it is activated. The publisher should not claim that data is not shared if a third-party service is actually loading.</p></section>
        <section><h2>7. Changing or withdrawing consent</h2><p>You can open <button type="button" className="inline-policy-button" onClick={openSettings}>Cookie settings</button> from this page or the footer at any time to change optional choices. Necessary local storage remains enabled only to retain the decision. Changing a choice affects future optional script loading in this browser; it does not retroactively delete data that a separately disclosed provider has already processed.</p></section>
        <section><h2>8. Your privacy requests and updates</h2><p>Before launch, the publisher must add a real contact address for privacy requests, corrections, and applicable access, deletion, or objection requests. This page should be reviewed whenever the domain, publisher identity, analytics configuration, advertising configuration, or third-party services change. The date above should change only after a substantive update.</p></section>
      </div>
      <section className="privacy-sources"><Cookie size={20} /><div><span className="eyebrow">Official references</span><p><a href="https://support.google.com/adsense/answer/7549925?hl=en" target="_blank" rel="noreferrer">How AdSense uses cookies</a> · <a href="https://www.google.com/about/company/user-consent-policy/" target="_blank" rel="noreferrer">Google EU user consent policy</a> · <a href="https://support.google.com/adsense/answer/13554116?hl=en" target="_blank" rel="noreferrer">Google CMP requirements for publishers</a></p></div></section>
    </section>
  </Layout>;
}
