/** Style note: Field Notes for Better Work — terms are a readable usage record with no faux legal theatrics. */
import { BookOpenCheck, CircleAlert, FileText, Gavel, Scale, ShieldCheck } from "lucide-react";
import Layout from "@/components/Layout";
import { SeoMeta } from "@/components/SeoMeta";
import { breadcrumbListSchema } from "@/components/SiteBreadcrumb";

const termsStyles = `
  .terms-page { position:relative; width:min(1070px,calc(100% - 48px)); margin:0 auto; padding:76px 0 120px; } .terms-page::before { content:"REFERENCE TRACK / TERMS RECORD / EDUCATIONAL USE"; position:absolute; top:125px; left:-38px; color:var(--green); border-left:1px solid var(--green); font-size:8px; font-weight:800; letter-spacing:.1em; line-height:1.55; text-transform:uppercase; writing-mode:vertical-rl; } .terms-page h1 { max-width:850px; margin:12px 0 17px; font-family:"DM Serif Display",Georgia,serif; font-size:clamp(48px,5.5vw,78px); font-weight:400; letter-spacing:-.06em; line-height:.96; } .terms-lede { max-width:720px; margin:0; color:#5b5d55; font-size:15px; line-height:1.75; } .terms-record { display:grid; grid-template-columns:repeat(3,1fr); gap:0; margin:50px 0 72px; border-top:1px solid var(--ink); border-left:1px solid var(--rule); } .terms-record div { min-height:112px; padding:19px 19px; border-right:1px solid var(--rule); border-bottom:1px solid var(--rule); } .terms-record strong { display:block; color:var(--green); font-size:9px; letter-spacing:.1em; text-transform:uppercase; } .terms-record span { display:block; margin-top:7px; color:#55574f; font-size:12px; line-height:1.55; } .terms-content { max-width:810px; margin-left:auto; } .terms-content section { display:grid; grid-template-columns:78px minmax(0,1fr); gap:28px; padding:35px 0; border-top:1px solid var(--rule); } .terms-content section:last-child { border-bottom:1px solid var(--rule); } .terms-number { color:var(--rust); font-family:"DM Serif Display",Georgia,serif; font-size:31px; letter-spacing:-.06em; line-height:.8; } .terms-content h2 { margin:0 0 11px; font-family:"DM Serif Display",Georgia,serif; font-size:30px; font-weight:400; letter-spacing:-.04em; line-height:1.05; } .terms-content p { margin:0 0 12px; color:#54564e; font-size:14px; line-height:1.8; } .terms-content p:last-child { margin-bottom:0; } .terms-content a { color:var(--green); border-bottom:1px solid var(--green); } .terms-note { display:grid; grid-template-columns:22px minmax(0,1fr); gap:12px; max-width:810px; margin:48px 0 0 auto; padding:20px; border-left:2px solid var(--green); background:var(--green-pale); } .terms-note svg { color:var(--green); } .terms-note p { margin:0; color:#3b5349; font-size:12px; line-height:1.65; } @media (max-width:760px) { .terms-page { width:min(100% - 28px,760px); padding:52px 0 82px; } .terms-page::before { display:none; } .terms-page h1 { font-size:46px; } .terms-lede { font-size:14px; } .terms-record { grid-template-columns:1fr; margin:34px 0 48px; } .terms-record div { min-height:0; } .terms-content { margin:0; } .terms-content section { grid-template-columns:42px minmax(0,1fr); gap:13px; padding:26px 0; } .terms-content h2 { font-size:26px; } .terms-content p { font-size:13px; line-height:1.72; } .terms-number { font-size:27px; } .terms-note { margin-top:32px; } }
`;

export default function Terms() { return <Layout><SeoMeta title="Terms of use" description="Workflow Library terms covering educational use, permitted conduct, AI limitations, intellectual property, third-party links, and policy updates." schema={({ origin, pageUrl }) => breadcrumbListSchema(origin, pageUrl, [{ label: "Home", href: "/" }, { label: "Terms of use" }])} /><style>{termsStyles}</style>
  <section className="terms-page"><span className="eyebrow">Terms of use</span><h1>Clear terms for<br />a practical library.</h1><p className="terms-lede">Effective date: 15 August 2026. These terms describe the permitted use of Workflow Library in its current public edition. They should be reviewed and completed with the publisher’s real legal identity, contact route, and governing-law details before a full commercial launch.</p>
    <div className="terms-record"><div><strong>Service</strong><span>Free educational guides for practical AI workflows.</span></div><div><strong>Current status</strong><span>Independent publication preparing its first public edition.</span></div><div><strong>Reader choice</strong><span>Read, share, and adapt the material responsibly.</span></div></div>
    <div className="terms-content">
      <section><span className="terms-number">01</span><div><h2>Acceptance and scope</h2><p>By accessing or using Workflow Library, you agree to these terms and the <a href="/privacy">Privacy & Cookie notice</a>. If you do not agree, do not use the site. These terms apply to the site’s guides, prompts, internal navigation, sharing controls, and other materials made available on the public site.</p></div></section>
      <section><span className="terms-number">02</span><div><h2>Educational content, not professional advice</h2><p>Workflow Library provides general educational material about working with AI. It does not provide legal, medical, financial, tax, employment, security, compliance, or other professional advice. A guide, prompt, or AI output is not a substitute for qualified advice or for a reader’s own judgment, source checking, approval process, or responsibility for a decision.</p></div></section>
      <section><span className="terms-number">03</span><div><h2>AI outputs and reader responsibility</h2><p>AI systems can be incomplete, inaccurate, biased, outdated, or unsuitable for a particular context. Readers remain responsible for the information they supply to an AI tool, the output they choose to rely on, and the actions they take. Do not submit confidential, personal, regulated, or sensitive information to an AI tool unless you understand the tool’s terms, permissions, and data practices.</p></div></section>
      <section><span className="terms-number">04</span><div><h2>Permitted use</h2><p>You may read, bookmark, link to, and share Workflow Library for lawful personal, educational, or internal work purposes. You may adapt a published prompt for your own task, provided you remain responsible for your context and output. You may not use the site to violate law, infringe rights, distribute harmful material, disrupt the service, scrape the site at a rate that impairs access, or misrepresent the publication as endorsing your work.</p></div></section>
      <section><span className="terms-number">05</span><div><h2>Content and intellectual property</h2><p>Unless a page says otherwise, Workflow Library’s text, organization, design, marks, and original materials are owned by or licensed to the publisher. Limited sharing through provided links is permitted. Reproducing substantial portions, creating a competing mirror, or using the name or marks in a way that suggests affiliation requires the publisher’s written permission when a public contact route is available.</p></div></section>
      <section><span className="terms-number">06</span><div><h2>Third-party services and links</h2><p>The site may link to third-party resources or offer sharing destinations. Those services are outside the publisher’s control and have their own terms and privacy notices. A link is provided for convenience and does not constitute an endorsement, warranty, partnership, or guarantee of availability.</p></div></section>
      <section><span className="terms-number">07</span><div><h2>Availability and changes</h2><p>The publisher may change, update, suspend, or remove a guide, feature, or link to maintain accuracy, security, or site quality. The publisher does not promise uninterrupted availability, error-free operation, a specific result from any workflow, or that a particular guide will remain available indefinitely.</p></div></section>
      <section><span className="terms-number">08</span><div><h2>Disclaimers and liability</h2><p>To the extent permitted by applicable law, the site is provided on an “as is” and “as available” basis without warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, or uninterrupted availability. The publisher is not responsible for indirect, incidental, special, consequential, or punitive damages arising from use of the site, reliance on a guide, or use of a third-party service. Some jurisdictions limit exclusions or limitations, so parts of this section may not apply to every visitor.</p></div></section>
      <section><span className="terms-number">09</span><div><h2>Governing law and contact</h2><p>The publisher will add the governing law, venue, and a real contact route before the public commercial edition is released. Until those details are published, no fictional address, legal entity, or jurisdiction is implied. Questions about the site’s editorial material, privacy practice, or terms should use the monitored contact route once it is made available on the <a href="/contact">Contact page</a>.</p></div></section>
      <section><span className="terms-number">10</span><div><h2>Updates to these terms</h2><p>The effective date changes when these terms change substantively. Continuing to use the site after a revised effective date means you accept the revised terms to the extent permitted by law. Material additions—such as paid services, accounts, direct data collection, or advertising technology—will be reflected in both these terms and the Privacy & Cookie notice before they take effect.</p></div></section>
    </div>
    <aside className="terms-note"><CircleAlert size={19} /><p>This working public-edition draft is intentionally specific about the services that are active today. A qualified attorney should review and complete the publisher identity, governing-law, venue, and contact sections before the terms are relied on for a commercial launch.</p></aside>
  </section>
</Layout>; }
