/** Style note: Field Notes for Better Work — topic pages are compact reference shelves, not keyword landing-page filler. */
import { ArrowLeft, ArrowUpRight, BookOpenCheck, CheckCircle2 } from "lucide-react";
import { Link, useParams } from "wouter";
import Layout from "@/components/Layout";
import GuideCard from "@/components/GuideCard";
import { SeoMeta } from "@/components/SeoMeta";
import { guides, topicClusters } from "@/lib/content";

const topicStyles = `
  .topic-hero { display:grid; grid-template-columns:minmax(0,1fr) 240px; gap:60px; width:min(1170px,calc(100% - 48px)); margin:auto; padding:96px 0 60px; border-bottom:1px solid var(--rule); } .topic-hero h1 { max-width:760px; margin:13px 0 18px; font-family:"DM Serif Display",Georgia,serif; font-size:clamp(48px,5.2vw,78px); font-weight:400; letter-spacing:-.06em; line-height:.96; } .topic-hero p { max-width:720px; margin:0; color:#565850; font-size:15px; line-height:1.8; } .topic-rail { align-self:end; padding:18px 0 0 20px; border-left:1px solid var(--green); } .topic-rail strong { display:block; color:var(--green); font-size:10px; letter-spacing:.1em; text-transform:uppercase; } .topic-rail p { margin-top:7px; font-size:12px; line-height:1.65; } .topic-intro { display:grid; grid-template-columns:.8fr 1.2fr; gap:9vw; width:min(1070px,calc(100% - 48px)); margin:auto; padding:76px 0 60px; } .topic-intro h2 { margin:10px 0 0; font-family:"DM Serif Display",Georgia,serif; font-size:38px; font-weight:400; letter-spacing:-.045em; line-height:1.05; } .topic-intro p { margin:0 0 14px; color:#575951; font-size:14px; line-height:1.82; } .topic-guide-grid { width:min(1170px,calc(100% - 48px)); margin:auto; padding:16px 0 120px; } .topic-guide-grid .guide-grid { margin-top:24px; } .topic-return { display:inline-flex; align-items:center; gap:7px; margin-bottom:20px; color:var(--green); font-size:12px; font-weight:800; } .topic-checks { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; width:min(1170px,calc(100% - 48px)); margin:0 auto 24px; padding:22px 0; border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); } .topic-checks span { display:flex; align-items:center; gap:8px; color:#4d5c54; font-size:12px; line-height:1.45; } .topic-checks svg { color:var(--green); flex:0 0 auto; } .topic-link-row { display:flex; flex-wrap:wrap; gap:8px; width:min(1170px,calc(100% - 48px)); margin:22px auto 0; } .topic-link-row a { padding:7px 10px; border:1px solid var(--rule); color:var(--green); font-size:10px; font-weight:800; letter-spacing:.07em; text-transform:uppercase; transition:background 160ms var(--ease-out),color 160ms var(--ease-out); } .topic-link-row a:hover { background:var(--green); color:#fffdf8; } @media (max-width:760px) { .topic-hero,.topic-intro { grid-template-columns:1fr; gap:28px; width:min(100% - 28px,760px); } .topic-hero { padding:72px 0 48px; } .topic-guide-grid,.topic-checks,.topic-link-row { width:min(100% - 28px,760px); } .topic-checks { grid-template-columns:1fr; gap:9px; } }
`;

export default function TopicPage() {
  const { topic: slug } = useParams<{ topic: string }>();
  const topic = topicClusters.find(item => item.slug === slug);
  if (!topic) return <Layout><SeoMeta title="Topic not found" description="This topic is not in the Workflow Library index." noIndex /><section className="not-found-wrap"><h1>This topic is not in the index.</h1><Link href="/guides" className="primary-button">Return to the library <ArrowUpRight size={16} /></Link></section></Layout>;
  const entries = topic.guideSlugs.map(guideSlug => guides.find(guide => guide.slug === guideSlug)).filter(Boolean);
  return <Layout><SeoMeta title={topic.seoTitle} description={topic.description} schema={({ origin, pageUrl }) => ({ "@type": "CollectionPage", name: topic.title, description: topic.description, url: pageUrl, mainEntity: { "@type": "ItemList", numberOfItems: entries.length, itemListElement: entries.map((guide, index) => ({ "@type": "ListItem", position: index + 1, name: guide!.title, url: `${origin}/guides/${guide!.slug}` })) } })} /><style>{topicStyles}</style>
    <section className="topic-hero"><div><Link href="/guides" className="topic-return"><ArrowLeft size={15} /> Back to the library</Link><span className="eyebrow">Workflow cluster / {topic.number}</span><h1>{topic.title}</h1><p>{topic.description}</p></div><aside className="topic-rail"><strong>Use this shelf when</strong><p>{topic.useWhen}</p></aside></section>
    <div className="topic-link-row" aria-label="Other workflow topics">{topicClusters.filter(item => item.slug !== topic.slug).map(item => <Link key={item.slug} href={`/workflows/${item.slug}`}>{item.shortTitle}</Link>)}</div>
    <section className="topic-intro"><div><span className="eyebrow">How to use these guides</span><h2>{topic.introTitle}</h2></div><div><p>{topic.intro}</p><p>Start with the task that already has enough context to inspect. Treat the generated output as a working surface, keep uncertainty visible, and use the related guide only when it helps the next human decision.</p></div></section>
    <section className="topic-checks"><span><CheckCircle2 size={17} /> Start from records you can inspect.</span><span><CheckCircle2 size={17} /> Make owners, sources, and limits visible.</span><span><CheckCircle2 size={17} /> Review before a draft becomes a commitment.</span></section>
    <section className="topic-guide-grid"><span className="eyebrow">Filed in this topic</span><div className="guide-grid">{entries.map(guide => <GuideCard guide={guide!} key={guide!.slug} />)}</div></section>
  </Layout>;
}
