/** Style note: Field Notes for Better Work — shared privacy styles preserve the paper-and-ink editorial system. */
export default function PrivacyEnhancements() {
  return <style>{`
    .legal-page { position:relative; } .legal-page::before { content:"REFERENCE TRACK / PRIVACY RECORD / CURRENT CONFIGURATION"; position:absolute; top:111px; left:-38px; color:var(--green); border-left:1px solid var(--green); font-size:8px; font-weight:800; letter-spacing:.1em; line-height:1.55; text-transform:uppercase; writing-mode:vertical-rl; }
    .privacy-policy-record { display:grid; grid-template-columns:repeat(3,1fr); margin:34px 0 0; border-top:1px solid var(--ink); border-left:1px solid var(--rule); } .privacy-policy-record>div { min-height:104px; padding:18px 19px; border-right:1px solid var(--rule); border-bottom:1px solid var(--rule); } .privacy-policy-record strong { display:block; color:var(--green); font-size:9px; letter-spacing:.1em; text-transform:uppercase; } .privacy-policy-record span { display:block; margin-top:7px; color:#595b53; font-size:11px; line-height:1.58; }
    .privacy-toc { display:flex; align-items:center; justify-content:space-between; gap:24px; margin-top:26px; padding:13px 0; border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); } .privacy-toc>span { display:inline-flex; align-items:center; gap:7px; color:var(--green); font-size:9px; font-weight:800; letter-spacing:.1em; text-transform:uppercase; white-space:nowrap; } .privacy-toc>div { display:flex; flex-wrap:wrap; justify-content:flex-end; gap:8px 18px; } .privacy-toc a { color:#4e514a; font-size:11px; font-weight:700; text-decoration:underline; text-decoration-color:var(--rule); text-underline-offset:4px; transition:color 160ms var(--ease-out),text-decoration-color 160ms var(--ease-out); } .privacy-toc a:hover { color:var(--green); text-decoration-color:var(--green); }
    .privacy-choice-panel { display:flex; align-items:center; justify-content:space-between; gap:24px; margin-top:28px; padding:22px 24px; border-top:2px solid var(--green); background:#edf5f1; }
    .privacy-choice-panel > div { display:flex; align-items:flex-start; gap:13px; } .privacy-choice-panel svg { flex:0 0 auto; margin-top:3px; color:var(--green); } .privacy-choice-panel .eyebrow { color:var(--green); } .privacy-choice-panel p { max-width:510px; margin:5px 0 0; color:#3e524a; font-size:12px; line-height:1.6; }
    .legal-content { counter-reset:privacy-section; margin-top:42px; } .legal-content section { position:relative; display:grid; grid-template-columns:74px minmax(0,1fr); gap:27px; padding:32px 0; } .legal-content section::before { counter-increment:privacy-section; content:counter(privacy-section,decimal-leading-zero); color:var(--rust); font-family:"DM Serif Display",Georgia,serif; font-size:31px; letter-spacing:-.06em; line-height:.8; } .legal-content section h2 { margin:0 0 11px; font-family:"DM Serif Display",Georgia,serif; font-size:30px; font-weight:400; letter-spacing:-.04em; line-height:1.05; } .legal-content section h2::first-letter { color:var(--ink); } .legal-content section p { margin:0 0 12px; color:#54564e; font-size:14px; line-height:1.8; } .legal-content section p:last-child { margin-bottom:0; } .legal-content strong { color:var(--green-deep); } .legal-content a { display:inline-flex; align-items:center; gap:3px; color:var(--green); border-bottom:1px solid var(--green); } .legal-content a:hover { color:var(--green-deep); } .inline-policy-button { padding:0; border-bottom:1px solid var(--green); background:transparent; color:var(--green); font-size:inherit; font-weight:700; }
    .privacy-implementation-note { display:grid; grid-template-columns:20px minmax(0,1fr); gap:11px; margin-top:18px; padding:15px 18px; border:1px solid #d8b9a4; background:#faf0e8; } .privacy-implementation-note svg { color:var(--rust); } .privacy-implementation-note strong { color:#693723; font-size:11px; } .privacy-implementation-note p { margin:4px 0 0; color:#6b5a50; font-size:12px; line-height:1.6; }
    .privacy-field-note { display:grid; grid-template-columns:22px minmax(0,1fr); gap:12px; margin:38px 0 0 auto; padding:18px 20px; border-left:2px solid var(--green); background:var(--green-pale); } .privacy-field-note svg { color:var(--green); } .privacy-field-note p { margin:0; color:#3b5349; font-size:12px; line-height:1.65; }
    .privacy-sources { display:flex; gap:14px; margin-top:56px; padding:22px 0; border-top:1px solid var(--rule); border-bottom:1px solid var(--rule); } .privacy-sources>svg { flex:0 0 auto; margin-top:2px; color:var(--rust); } .privacy-sources p { margin:4px 0 0; color:#5b5d55; font-size:12px; line-height:1.7; } .privacy-sources a { color:var(--green); border-bottom:1px solid var(--green); }
    @media (max-width:760px) { .legal-page::before { display:none; } .privacy-policy-record { grid-template-columns:1fr; } .privacy-policy-record>div { min-height:0; } .privacy-toc { align-items:flex-start; flex-direction:column; gap:9px; } .privacy-toc>div { justify-content:flex-start; } .legal-content { margin-top:27px; } .legal-content section { grid-template-columns:42px minmax(0,1fr); gap:13px; padding:26px 0; scroll-margin-top:88px; } .legal-content section h2 { font-size:26px; } .legal-content section p { font-size:13px; line-height:1.72; } .legal-content section::before { font-size:27px; } } @media (max-width:620px) { .privacy-choice-panel { flex-direction:column; align-items:stretch; margin-top:24px; } .privacy-choice-panel .primary-button { width:100%; } .privacy-toc>div { gap:9px 15px; } .privacy-implementation-note { padding:14px 15px; } }
  `}</style>;
}
