/** Style note: Field Notes for Better Work — recommendations form a small indexed shelf, never a generic traffic widget. */
import { ArrowRight, BookOpenCheck, ChevronRight } from "lucide-react";
import { Link } from "wouter";
import { getRecommendedGuideRecords, type Guide } from "@/lib/content";

const recommendationStyles = `
  .recommended-reading { margin-top:74px; padding:30px 0 0; border-top:2px solid var(--ink); } .recommended-heading { display:grid; grid-template-columns:92px minmax(0,1fr) auto; gap:20px; align-items:end; padding-bottom:22px; border-bottom:1px solid var(--rule); } .recommended-index { color:var(--rust); font-family:"DM Serif Display",Georgia,serif; font-size:40px; letter-spacing:-.07em; line-height:.8; } .recommended-heading h2 { margin:6px 0 0; font-family:"DM Serif Display",Georgia,serif; font-size:34px; font-weight:400; letter-spacing:-.045em; line-height:1.02; } .recommended-heading p { max-width:300px; margin:0; color:#62645c; font-size:11px; line-height:1.6; } .recommended-list { display:grid; grid-template-columns:repeat(3,1fr); } .recommended-item { position:relative; display:flex; flex-direction:column; min-height:205px; padding:24px 23px 22px; border-right:1px solid var(--rule); border-bottom:1px solid var(--rule); color:var(--ink); transition:background 180ms var(--ease-out),color 180ms var(--ease-out); } .recommended-item:first-child { border-left:1px solid var(--rule); } .recommended-item:hover { background:var(--green-pale); } .recommended-item:hover .recommended-arrow { color:var(--green); transform:translateX(3px); } .recommended-kicker { display:flex; justify-content:space-between; gap:8px; color:var(--green); font-size:9px; font-weight:800; letter-spacing:.09em; text-transform:uppercase; } .recommended-item h3 { margin:21px 0 8px; font-family:"DM Serif Display",Georgia,serif; font-size:24px; font-weight:400; letter-spacing:-.035em; line-height:1.05; } .recommended-item p { margin:0; color:#5e6058; font-size:12px; line-height:1.58; } .recommended-arrow { margin-top:auto; padding-top:15px; color:#6d6f66; transition:color 180ms var(--ease-out),transform 180ms var(--ease-out); } .recommended-browse { display:inline-flex; align-items:center; gap:6px; color:var(--green); font-size:10px; font-weight:800; white-space:nowrap; } @media (max-width:760px) { .recommended-reading { margin-top:52px; padding-top:23px; } .recommended-heading { grid-template-columns:45px minmax(0,1fr); gap:12px; padding-bottom:17px; } .recommended-index { font-size:30px; } .recommended-heading h2 { font-size:27px; } .recommended-heading p { grid-column:2; margin-top:3px; font-size:10px; } .recommended-browse { grid-column:2; margin-top:4px; } .recommended-list { grid-template-columns:1fr; } .recommended-item { min-height:0; padding:20px 19px; border-left:1px solid var(--rule); } .recommended-item h3 { margin:14px 0 7px; font-size:23px; } .recommended-arrow { position:absolute; right:18px; bottom:21px; padding:0; } .recommended-item p { padding-right:30px; } }
`;

export default function RecommendedReading({ guide }: { guide: Guide }) {
  const recommendations = getRecommendedGuideRecords(guide);
  if (!recommendations.length) return null;
  return <section className="recommended-reading" aria-labelledby="recommended-reading-title"><style>{recommendationStyles}</style><div className="recommended-heading"><span className="recommended-index">06</span><div><span className="eyebrow">Recommended reading</span><h2 id="recommended-reading-title">Keep the work moving.</h2></div><div><p>These guides share a real task connection with the one you just read.</p><Link className="recommended-browse" href="/guides">Browse the full library <BookOpenCheck size={14} /></Link></div></div><nav className="recommended-list" aria-label="Recommended guides">{recommendations.map(({ guide: item, reason }, index) => <Link className="recommended-item" key={item.slug} href={`/guides/${item.slug}`}><span className="recommended-kicker"><span>{String(index + 1).padStart(2, "0")} / {item.category}</span><span>{reason}</span></span><h3>{item.title}</h3><p>{item.dek}</p><ArrowRight className="recommended-arrow" size={17} aria-hidden="true" /></Link>)}</nav></section>;
}
